name: 'Phrase sync'
description: 'Syncs Phrase via en.json upload'
inputs:
  phrase_token: # available as process.env.INPUT_PHRASE_TOKEN
    description: 'Phrase API access token'
    required: true
  project_id: # available as process.env.PROJECT_ID
    description: 'Phrase project id'
    required: true
  english_locale_file_path: # available as process.env.INPUT_ENGLISH_LOCALE_FILE_PATH
    description: 'Path to english locale file'
    required: true
  reset:
    description: 'If this is "true", the action will reset the exclusions instead'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
