name: 'Phrase sync'
description: 'Syncs Phrase via en.json upload'
inputs:
  phrase-token: # available as process.env.INPUT_PHRASE_TOKEN
    description: 'Phrase API access token'
    required: true
  project-id: # available as process.env.PROJECT_ID
    description: 'Phrase project id'
    required: true
  reset:
    description: 'If this is "true", the action will reset the exclusions instead'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
